image: dchevell/docker-release-maker:latest
clone:
  depth: full

pipelines:
  custom:
    create-release-base-5:
      - step:
          script:
            - git fetch --all
            - export BASE_BRANCH=base-5
            - export BASE_VERSION=5
            - export DOCKER_REPO=atlassian/bitbucket-server
            - export DOCKERFILE_VERSION_STRING=BITBUCKET_VERSION
            - export GIT_USER=bbs-pipelines-bot
            - export GIT_EMAIL=bbs-pipelines-bot@atlassian.com
            - export MAC_PRODUCT_KEY=bitbucket
            - python /usr/src/app/create_release.py
    test:
      - step:
          image: docker:stable-git
          script:
            # Run bitbucket docker image
            - mkdir -p data
            - |
                docker run -v $(pwd)/data:/var/atlassian/application-data/bitbucket \
                  --name="bitbucket" -d -p 7990:7990 -p 7999:7999 atlassian/bitbucket-server
            # Run tests
            - git show origin/scripts:scripts/test-bitbucket-status.sh | install -m 0755 /dev/fd/0 test-bitbucket-status.sh
            - ./test-bitbucket-status.sh
          services:
            - docker

  branches:
    base-5:
      - step:
          script:
            - git fetch --all
            - export BASE_BRANCH=base-5
            - export BASE_VERSION=5
            - export DOCKER_REPO=atlassian/bitbucket-server
            - export DOCKERFILE_VERSION_STRING=BITBUCKET_VERSION
            - export GIT_USER=bbs-pipelines-bot
            - export GIT_EMAIL=bbs-pipelines-bot@atlassian.com
            - export MAC_PRODUCT_KEY=bitbucket
            - python /usr/src/app/update_release.py
