image: atlassian/docker-release-maker:latest

pipelines:
  custom:
    base-6-create-releases:
      - step:
          services:
            - docker
          script:
            - export BASE_VERSION='6'
            - export DEFAULT_RELEASE='true'
            - export DOCKER_REPO='atlassian/bitbucket-server'
            - export DOCKERFILE_VERSION_ARG='BITBUCKET_VERSION'
            - export MAC_PRODUCT_KEY='bitbucket'
            - export TAG_SUFFIXES='jdk8,ubuntu'
            - echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_USERNAME} --password-stdin
            - python /usr/src/app/run.py --create
    base-6-create-custom-release:
      - variables:
          - name: BITBUCKET_VERSION
          - name: DOCKER_TAG
      - step:
          services:
            - docker
          script:
            - echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_USERNAME} --password-stdin
            - docker build -t atlassian/bitbucket-server:${DOCKER_TAG} --build-arg BITBUCKET_VERSION=${BITBUCKET_VERSION} .
            - docker push atlassian/bitbucket-server:${DOCKER_TAG}
  branches:
    base-6:
      - step:
          services:
            - docker
          script:
            - export BASE_VERSION='6'
            - export DEFAULT_RELEASE='true'
            - export DOCKER_REPO='atlassian/bitbucket-server'
            - export DOCKERFILE_VERSION_ARG='BITBUCKET_VERSION'
            - export MAC_PRODUCT_KEY='bitbucket'
            - export TAG_SUFFIXES='jdk8,ubuntu'
            - echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_USERNAME} --password-stdin
            - python /usr/src/app/run.py --update